#!/usr/bin/env bash
# https://stackoverflow.com/questions/1885525/how-do-i-prompt-a-user-for-confirmation-in-bash-script
read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	rm "$(readlink -f ~/.base16_theme)"
	theme
fi
