#!/bin/bash

# gets xbmicons working
~/.xinitrc

swm-statusbar &
#until swm-statusbar &>/dev/null; do
#    sleep 1
#done &

while true; do
    change-desktop
    sleep 180
done &

sudo tlp start
redshift &
eval "$(ssh-agent -s)" &
chrome &
tmux &
st -e tmux new -s os || st -e tmux attach -t os &
st -e tmux new -s misc || st -e tmux attach -t misc &
st -e tmux new -s PL || st -e tmux attach -t PL &

dwm

pkill --oldest --signal TERM -f chrome
while pkill -0 chrome; do sleep .25; done # wait for chrome to safely close
pkill redshift
pkill swm-statusbar
exit
