#!/bin/bash

# gets xbmicons working
~/.xinitrc

swm-statusbar &
#until swm-statusbar &>/dev/null; do
#    sleep 1
#done &

while true; do
    change-desktop
    sleep 180
done &

fluxgui &
rescuetime &

dwm

pkill --oldest --signal TERM -f chrome
pkill --oldest --signal TERM -f opera
while pkill -0 chrome; do sleep .25; done # wait for chrome to safely close
while pkill -0 opera; do sleep .25; done # wait for opera to safely close
pkill rescuetime
pkill fluxgui
pkill swm-statusbar
exit
