#!/bin/bash

# Colour codes from dwm/config.h
colour_gry="\x01" # grey on black
colour_wht="\x02" # white on black
colour_dgry="\x04" # darkgrey on black
colour_blk="\x05" # black on darkgrey
colour_red="\x06" # red on black
colour_grn="\x07" # green on black
colour_dylw="\x08" # orange on black
colour_ylw="\x09" # yellow on black
colour_blu="\x0A" # blue on darkgrey
colour_mag="\x0B" # magenta on darkgrey
colour_cyn="\x0C" # cyan on darkgrey

# Icon glyphs from font xbmicons.pcf
glyph_msc="\uE00E"
glyph_cpu="\uE00F"
glyph_mem="\uE010"
glyph_dl="\uE011"
glyph_ul="\uE012"
glyph_com="\uE013"
glyph_eml="\uE014"
glyph_vol="\uE015"
glyph_light="\uE006"
glyph_tim="\uE016"
glyph_tor="\uE017"
glyph_wifi="\uE01E"
glyph_bat="\uE01F"
sep_solid="\uE01A"
sep_line="\uE01B"
sep_bar="\uE020"

print_mem_used() {
	mem_used="$(free -m | awk 'NR==3 {print $3}')"
	echo -ne "${sep_line} ${glyph_mem} ${mem_used}M "
}

print_volume_and_brightness() {
	state="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)\]$/\1/')"
	if [ "$state" = "on" ]
	then
		volume="$(amixer get Master | tail -n1 | sed -r 's/.*\[(.*)%\].*/\1/')"
	else
		volume="0"
	fi

	brightness="$(printf "%.*f" 0 `xbacklight -get`)"

	echo -ne "${colour_dgry}${sep_solid}${colour_mag} ${glyph_light} ${brightness} ${sep_line} ${glyph_vol} ${volume}% "
}

print_datetime() {
	datetime="$(date "+%a %d %b ${sep_line} %H:%M:%S")"
	echo -ne "${colour_blk}${sep_solid}${colour_wht} ${glyph_tim} ${datetime} "
}

print_battery() {
	battery=$(( `cat /sys/class/power_supply/BAT0/energy_now` * 100 / `cat /sys/class/power_supply/BAT0/energy_full` ))
	battery_state=`cat /sys/class/power_supply/BAT0/status`
	echo -ne "${colour_dgry}${sep_solid}${colour_cyn} ${glyph_bat} ${battery} ${battery_state} "
}

print_wifi() {
	essid=$( /sbin/iwgetid -r ) 
	if [ $DWM_ESSID == "" ]
	then
		essid="--"
	fi
	echo -ne "${colour_blk}${sep_solid}${colour_dylw} ${glyph_wifi} ${essid} "
}

# network (from: http://dzen.geekmode.org/dwiki/doku.php?id=dzen:network-meter)
# cpu (from: https://bbs.archlinux.org/viewtopic.php?pid=661641#p661641)
rx_old=$(cat /sys/class/net/wlan0/statistics/rx_bytes)
tx_old=$(cat /sys/class/net/wlan0/statistics/tx_bytes)

while true; do
	# get new cpu idle and total usage
	eval $(awk '/^cpu /{print "cpu_idle_now=" $5 "; cpu_total_now=" $2+$3+$4+$5 }' /proc/stat)
	cpu_interval=$((cpu_total_now-${cpu_total_old:-0}))
	# calculate cpu usage (%)
	let cpu_used="100 * ($cpu_interval - ($cpu_idle_now-${cpu_idle_old:-0})) / $cpu_interval"

	# get new rx/tx counts
	rx_now=$(cat /sys/class/net/wlan0/statistics/rx_bytes)
	tx_now=$(cat /sys/class/net/wlan0/statistics/tx_bytes)
	# calculate the rate (K) and total (M)
	let rx_rate=($rx_now-$rx_old)/1024
	let tx_rate=($tx_now-$tx_old)/1024
	#  let rx_total=$rx_now/1048576
	#  let tx_total=$tx_now/1048576

	# output vars
	print_cpu_used() {
		printf "%-14b" "${colour_dgry}${sep_solid}${colour_blu} ${glyph_cpu} ${cpu_used}%"
	}
	print_rx_rate() {
		printf "%-15b" "${colour_blk}${sep_solid}${colour_grn} ${glyph_dl} ${rx_rate}K"
	}
	print_tx_rate() {
		printf "%-14b" "${colour_gry}${sep_line}${colour_red} ${glyph_ul} ${tx_rate}K"
	}

	# Pipe to status bar, not indented due to printing extra spaces/tabs
	xsetroot -name "
$(print_battery)\
$(print_wifi)\
$(print_cpu_used)$(print_mem_used)\
$(print_rx_rate)$(print_tx_rate)\
$(print_volume_and_brightness)\
$(print_datetime)
"

	# reset old rates
	rx_old=$rx_now
	tx_old=$tx_now
	cpu_idle_old=$cpu_idle_now
	cpu_total_old=$cpu_total_now
	# loop stats every 1 second
	sleep 1
done
