#!/usr/bin/env bash
if test "$BASH" = "" || "$BASH" -uc "a=();true \"\${a[@]}\"" 2>/dev/null; then
	# Bash 4.4, Zsh
	set -euo pipefail
else
	# Bash 4.3 and older chokes on empty arrays with set -u.
	set -eo pipefail
fi
shopt -s nullglob globstar

YEAR=$(date +%Y)

DAY=$(date -d "last-sunday" +%d)
MONTH=$(date -d "last-sunday" +%m)
FILE=/tmp/weeklydiarydiary-$MONTH-$DAY.html

echo "" > $FILE
for i in {6..0}; do
    DAY=$(date -d "last-sunday-${i} day" +%d)
    MONTH=$(date -d "last-sunday-${i} day" +%m)
    echo "<iframe width='49.5%' height='47%' src='https://www.dailydiary.com/myquestions/342540/how-did-your-day-go/journal?perpage=1&year=$YEAR&page=$DAY&month=$MONTH'></iframe>" >> $FILE
done

google-chrome $FILE
