#!/usr/bin/env bash
if test "$BASH" = "" || "$BASH" -uc "a=();true \"\${a[@]}\"" 2>/dev/null; then
	# Bash 4.4, Zsh
	set -euo pipefail
else
	# Bash 4.3 and older chokes on empty arrays with set -u.
	set -eo pipefail
fi
shopt -s nullglob globstar

SUNDAY_OFFSET=$(date -d today +%w)

for i in {6..0}; do
    OFFSET=$((i + SUNDAY_OFFSET))
    DAY=$(date -d "today -${OFFSET} days" +%d)
    MONTH=$(date -d "today -${OFFSET} days" +%m)
    YEAR=$(date -d "today -${OFFSET} days" +%Y)
    xdg-open "https://www.dailydiary.com/myquestions/342540/how-did-your-day-go/journal?perpage=1&year=${YEAR}&page=${DAY}&month=${MONTH}"
done
